online_courses/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.index_view, name='index' ),
     path('course/<str:id>', views.course_view, name='course'),
    path('course/course-lesson/<str:id>', views.course_lesson_view, name='course_lesson'),
    path('signup', views.signup_view, name='signup'),
    path('signin', views.signin_vew, name='signin'),
    path('signout', views.logout_view, name='logout'),
    path('account', views.account_view, name='account'),
    path('a-courses', views.account_courses, name='account_courses'),
    path('a-course/<str:id>', views.account_course, name='account_course'),
    path('a-lesson/<str:id>', views.account_lesson, name='account_lesson'),
    path('ad-account', views.admin_account_view, name='admin_account'),
    path('ad-courses', views.admin_courses, name='admin_courses'),
    path('843s98eadmidfn235a/account/addcourse', views.add_course, name='add_course'),
    path('843s98eadmidfn235a/account/modify/<str:id>', views.modify_course, name='modify_course'),
    path('843s98eadmidfn235a/account/modifyl/<str:id>', views.modify_lesson, name='modify_lesson'),
    path('ad-created-course/<str:id>', views.created_course, name='created_course'),
    path('843s98eadmidfn235a/account/c/<str:id>', views.create_curriculum, name='create_curriculum'),
    path('843s98eadmidfn235a/account/addcourse/lesson/<str:id>', views.create_lesson, name='create_lesson'),   
    path('843s98eadmidfn235a/account/courses/<str:id>', views.admin_course_curriculum, name='admin_course_curriculum'),
    path('flight', views.flight),
   ]

online_courses/models.py
from django.db import models
from django.contrib.auth.models import User
from random import choice
import string



# Create your models here.

class Courses(models.Model):
    id = models.CharField(primary_key=True,unique=True, max_length=22)
    title   = models.CharField(max_length=80, null=True)
    price = models.IntegerField(null=True, blank=True)
    description =models.TextField(max_length=500, null=True, blank=True)
    more = models.TextField(max_length=20000, null=True, blank=True)
    time  = models.TimeField(auto_now=True)
    date  = models.DateField(auto_now=True)
    image  = models.ImageField(upload_to='uploads/%Y/%m/%d/', default="uploads/image-icon.jpg")
    def __str__(self):
        return f'{self.title} - {self.date}'
    user = models.ManyToManyField(User, related_name="students")

class Course_curriculums(models.Model):
    name = models.CharField(max_length=30, blank=False)   
    courses = models.ForeignKey(Courses, on_delete=models.CASCADE, related_name="days")
    def __str__(self) -> str:
        return self.name

class Course_lessons(models.Model):
    id = models.CharField(primary_key=True,unique=True, max_length=22)
    lesson_name =  models.CharField(max_length=70, blank=False, null=False)
    lesson_file= models.FileField(upload_to='uploads/tutorials/videos/', null=True)
    key_points = models.TextField(max_length=1000, blank=False, null=False)
    courses = models.ForeignKey(Courses, on_delete=models.CASCADE, related_name="thetop")
    curriculums = models.ForeignKey(Course_curriculums, on_delete=models.CASCADE)
    visited = models.BooleanField(default=False)


    def __str__(self) -> str:
        return self.lesson_name
    
class Home_contents(models.Model):
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/', blank=True, default="uploads/default-thumbnail.jpg")
    discription = models.TextField(max_length=1000)
    time        = models.TimeField(auto_now=True)

    def __str__(self) -> str:
        return self.discription

class Flight(models.Model):
    f_from = models.CharField(max_length=24)
    f_to = models.CharField(max_length=45)
    duration =models.IntegerField()

class Passengers(models.Model):
    flight = models.ForeignKey(Flight, on_delete=models.CASCADE, related_name='passengers')
    name = models.CharField(max_length=24)

class laguage(models.Model):
    owner = models.ForeignKey(Passengers, on_delete=models.CASCADE, related_name="pass_lag")
    kg = models.IntegerField()

online_courses/templates/online_courses/admin_files/add_course.html
{% extends 'online_courses/base/base.html' %}
{% load static %}

{% block title %} 
addcourse | drizzle-school
{% endblock %}

{% block body %}

<div>
    
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ add_course_form.as_p }}
        <br>
        <input type="submit" name="submmit_course" value="Create"
        style=" padding-left: 30px; padding-right: 30px;" ></input>
    </form>

</div>
{% endblock %}

online_courses/templates/online_courses/admin_files/admin_account.html
{% extends 'online_courses/base/base.html' %}
{% load static %}

{% block title %} 
account | drizzle-school
{% endblock %}

{% block body %}
<div>
                {% for message in messages%}
                <p id="success-message">{{message}}</p>
                {% endfor %}
  
    <h1>superuser account</h1>
    <p>Username: {{ fullname }}</p>
    <a href="{% url 'logout' %}">Sign out</a> <br><br>
    
    <div>
        <a href="{% url 'admin_courses' %}">Courses</a> <br>
        <a href="{% url 'add_course' %}">Add course</a><br>
        <a href="">Modify <b>About us</b> page</a><br>
        <a href="">School members</a><br>
        <a href="">Create user</a><br>
    </div>

</div>
{% endblock %}

online_courses/templates/online_courses/admin_files/course.html
{% extends 'online_courses/base/base.html' %}
{% load static %}

{% block title %} 
Course | drizzle-school
{% endblock %}

{% block body %}
<div>
    <div>
       
           
                <div>
                    <p><b>{{ course.title }}</b></p>

                        <style>
                            table,td{
                                border-collapse: collapse;
                                padding: 15px;
                            }
                            th{
                                background-color: darkgrey;
                            }
                        </style>
                    
                        <table>
                          <tbody>
                            {% for curriculum in curriculums %}
                            <th>{{ curriculum.name }}</th><th></th>
                            {% for lesson in lessons%}
                            {% if curriculum.id == lesson.curriculums.id %}
                            <tr>
                                <td>{{lesson.lesson_name}}</td>
                                <td><a href="/843s98eadmidfn235a/account/modifyl/{{lesson.id}}" style="color:green"><i>Modify</i></a></td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                            <tr><td><a href="/843s98eadmidfn235a/account/addcourse/lesson/{{ curriculum.id }}" ><i>Add new lesson</i></a></td><td></td></tr>
                            {% endfor %}
                            
                          </tbody>
                            
                        </table>
                                
                                
                                    
                                
                                           
                  
                    <a href="" style="color: red;"><i>Delete all curriculum in this course</i></a>

                 
   
    </div>
</div>
{% endblock %}

online_courses/templates/online_courses/admin_files/courses.html
{% extends 'online_courses/base/base.html' %}
{% load static %}

{% block title %} 
courses | drizzle-school
{% endblock %}  
{% block body %}
<div>
    <div>
        {% for course in courses %}

                <div id="course">
                    <img src="{{ course.image }}" alt="course-image"
                    width="300px" height="200px">
                    <h4><b>Title</b>:{{ course.title }}<a href="/843s98eadmidfn235a/account/modify/{{course.id}}" style="color:green">  <i>Rename</i></a></h4>
                    <p><b>Created on</b>: {{ course.date }} {{ course.time }}</p>
                    <p><b>Price</b>: {{ course.price }} <a href="/843s98eadmidfn235a/account/modify/{{course.id}}" style="color:green"><i>Adjust</i></a></p>
                    <p><b>Description</b>: {{ course.description }} <a href="/843s98eadmidfn235a/account/modify/{{course.id}}" style="color:green"><i>Modify</i></a></p>
                    <p><b>More about the course</b>: {{ course.more }} <a href="/843s98eadmidfn235a/account/modify/{{course.id}}" style="color:green"><i>Modify</i></a></p>
                    <p><b>Enrolled Students: {{ course.user.all.count }}</b></p>
                    
                    <div>
                        <p><b><a href="/843s98eadmidfn235a/account/courses/{{ course.id }}">course curriculum</a></b></p>
                        
                    </div>
                    <div>
                        
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="hidden" value="{{  course.id }}" name="deleted_coourse_id">
                            <input type="submit" onclick="" value="Delete course" name="delete_course" style="background-color: red; color: aliceblue;">
                        </form>

                        <script>
                            function conf(){
                                yes = window.confirm("Are you sure you want to permanently delete this course!")
                                if (yes){
                                    return true;
                                }
                                else{
                                    return false;
                                }
                            }
                        </script>
                    </div>
                    <hr><br><br>

                </div>

        {% endfor %}
        

    </div>
</div>
{% endblock %}

online_courses/templates/online_courses/admin_files/create_curriculum.html
{% extends 'online_courses/base/base.html' %}
{% load static %}

{% block title %} 
addcourse | drizzle-school
{% endblock %}

{% block body %}
<div>
                {% for message in messages%}
                <p id="success-message">{{message}}</p>
                {% endfor %}

    <h3>{{ course.title }}</h3>
    {% if curriculums %}
        <table>
        <tbody>
        {% for curriculum in curriculums %}
        <tr>
            <td>{{ curriculum.name }}</td>
            <td><a href="/843s98eadmidfn235a/account/addcourse/lesson/{{ curriculum.id }}" style="color:green"><i>Add lessons</i></a></td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
    {% endif %}
    <h4>Create curriculum</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ curriculum_form.as_p }}
        <br>
        <input type="submit" name="create_curriculum" value="Create"
        style=" padding-left: 30px; padding-right: 30px;" ></input>
    </form>

</div>
{% endblock %}

online_courses/templates/online_courses/admin_files/create_lesson.html
{% extends 'online_courses/base/base.html' %}
{% load static %}

{% block title %} 
addcourse | drizzle-school
{% endblock %}

{% block body %}
<style>
    table,td{
        border: 1px solid gray;
        border-collapse: collapse;
        padding: 15px;
    }
    th{
        background-color: darkgrey;
        
    }
</style>

<div>
        
    <h3>{{ course.title }}</h3>
    {% if curriculum %}
    <h4>Curriculum: {{ curriculum.name }}</h4>
        <table>
            <thead>
                <th>Lesson</th> 
                <th style="padding-left: 190px;">Duration</th>
            </thead>
            <tbody>
        {% for lesson in lessons %}
        {% if curriculum.id == lesson.curriculums.id %}
                <tr>
                    <td><a href="">{{lesson.lesson_name}}</a></td>
                    <td><i>__hrs:__min</i></td>
                </tr>
        {% endif %}
        {% endfor %}
            </tbody>
        </table>
    {% endif %}


        <h4>Create Lesson</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ lesson_form.as_p }}
        <br>
        <input type="submit" name="create_lesson" value="Create "
        style=" padding-left: 30px; padding-right: 30px;" ></input>
    </form>

</div>
{% endblock %}

online_courses/templates/online_courses/admin_files/created_course.html
{% extends 'online_courses/base/base.html' %}
{% load static %}

{% block title %} 
Home | drizzle-school
{% endblock %}  
{% block body %}
<div>
    <div>
     
            <a href="/843s98eadmidfn235a/account/c/{{course.id}}">
                <div id="course">
                    <img src="{{ course.image }}" alt="course-image">
                    <h3>{{ course.title }}</h3>

                </div>
            </a>
 
    </div>
</div>
{% endblock %}

online_courses/templates/online_courses/admin_files/modify_course.html
{% extends 'online_courses/base/base.html' %}
{% load static %}

{% block title %} 
Modifycourse | drizzle-school
{% endblock %}

{% block body %}
<style>
    #id_title, #id_price, #id_description, #id_more{
        border: none;
    }
    #save{
        color: green;
        padding-left: 20px;
        padding-right: 20px;
    }
</style>

<div>


    <form action="" method="post">
        {% csrf_token %}
        <h3>Title: {{ modify_form.title }} <input type="submit" value="save" name="save" id="save"></h3> 
        <p><b>Price</b>: {{ modify_form.price }} <input type="submit" value="save" name="save" id="save"></p>
        <p><b>Description</b>: {{ modify_form.description }} <input type="submit" value="save" name="save" id="save"></p>
        <p><b>More</b>: {{ modify_form.more }} <input type="submit" value="save" name="save" id="save"></p>
        <br>

    </form>

</div>
{% endblock %}

online_courses/templates/online_courses/admin_files/modify_lesson.html
{% extends 'online_courses/base/base.html' %}
{% load static %}

{% block title %} 
addcourse | drizzle-school
{% endblock %}

{% block body %}

<div>     
    <h3>{{ course.title }}</h3>
    {% if curriculum %}
    <h4>Curriculum: {{ curriculum.name }}</h4>

    {% endif %}
     <h4>modify Lesson</h4>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ lesson_form.as_p }}
        <br>
        <input type="submit" name="modify_lesson" value = "save"
        style=" padding-left: 30px; padding-right: 30px;" ></input>
    </form>

</div>
{% endblock %}












